name: smile
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_auth: ^0.20.1
  firebase_core: ^0.7.0 
  firebase_database: ^6.0.0  
  firebase_storage: ^7.0.0
  firebase_analytics: ^5.0.2
  font_awesome_flutter: ^8.11.0
  # images_picker: ^0.0.8
  image_picker: ^0.6.7+22
  provider: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
          style: italic
    - family: DMSansBold
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          style: italic
  
